#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           turntable,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           feedmotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	turnFlashlightOn(flashlight, -127);
	while (true)
	{
		if (SensorValue[linefollow] > 2000 )
		{
			setServo(turntable, 75);
			turnLEDOn(green);
			wait(1);
			turnLEDOff(green);
		}
		else
		{
			setServo(turntable, -75);
			turnLEDOn(red);
			wait(1);
			turnLEDOff(red);
		}
		
		wait(7);

		setServo(feedmotor,-127);
		turnLEDOn(yellow);
		wait(3);
		setServo(feedmotor,127);
		turnLEDOff(yellow);
	}
}
