#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           turntable,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           feedmotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()                               
{
	turnFlashlightOn(flashlight, -127);     
	while (true)                            
	{

		if (SensorValue[linefollow] > 2000 )     
		{
			setServo(turntable, 75);           
		}
		else                                  
		{
			setServo(turntable, -75);           
		}
		wait(7);           
		

		setServo(feedmotor,-127);           
		wait(3);                            
		setServo(feedmotor,127);             

	}
}
