#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftRail,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightRail,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//this robot has a platform to rasin and lower moble goals//

task main()
{

	while(1 == 1)
	{
		//back wheels
		motor[rightMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[leftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
		//rails
		motor[rightRail]  = (vexRT[Ch3])/2;
		motor[leftRail] = (vexRT[Ch3])/2;
	}
}
