#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftRail,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightRail,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//this robot has aplatform to rasin adn lower moble goals//

task main()
{

	while(1 == 1)
	{
		//back wheels
		motor[rightMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[leftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;

		// right rail
		if(vexRT[Btn5D] == 1)       	//If 5U is pressed
		{
			motor[rightRail] = 127;    	//raise arm.
		}
		else if(vexRT[Btn5U] == 1)  	//if 5D is pressed
		{
			motor[rightRail] = -75;   	//lower arm
		}
		else                      		//neither is pressed
		{
			motor[rightRail] = 0;      	//hold arm
		}
		//left rail
		if(vexRT[Btn5D] == 1)       	//If 5U is pressed
		{
			motor[leftRail] = 127;    	//raise arm.
		}
		else if(vexRT[Btn5U] == 1)  	//if 5D is pressed
		{
			motor[leftRail] = -75;   	//lower arm.
		}
		else                      		//neither is pressed
		{
			motor[leftRail] = 0;      	//hold arm
		}
	}
}
