#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftRail,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightRail,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//this robot has a platform to rasin and lower moble goals//

task main()
{
	while(1 == 1)
	{
		//right joy
		motor[leftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		//left joy
		motor[rightMotor] = (vexRT[Ch3] - vexRT[Ch4])/2;
		// right rail
		if(vexRT[Btn7U] == 1)       	//If 6U is pressed
		{
			motor[rightRail] = 127;  		//close claw
		}
		else if(vexRT[Btn7D] == 1)  	//if 6D is pressed
		{
			motor[rightRail] = -127; 		//open claw
		}
		else                      		//if neather is pressed
		{
			motor[rightRail] = 0;    		//do nothing with claw
		}
		//left rail
		if(vexRT[Btn7U] == 1)       	//If 6U is pressed
		{
			motor[leftRail] = 127;  		//close claw
		}
		else if(vexRT[Btn7D] == 1)  	//if 6D is pressed
		{
			motor[leftRail] = -127; 		//open claw
		}
		else                      		//if neather is pressed
		{
			motor[leftRail] = 0;    		//do nothing with claw
		}
	}
}
