#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rotate,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//standerd clawbot with rotaing arm//

task main()
{

	while(1 == 1)
	{
		//wheels
		motor[leftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[rightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
		//rotate
		motor[rotate]  = (vexRT[Ch3] + vexRT[Ch4])/2;
		motor[rotate] = (vexRT[Ch4] - vexRT[Ch4])/2;
		// arm
		if(vexRT[Btn5U] == 1)       	//If 5U is pressed
		{
			motor[armMotor] = 127;    	//raise arm.
		}
		else if(vexRT[Btn5D] == 1)  	//if 5D is pressed
		{
			motor[armMotor] = -75;   	//lower arm
		}
		else                      		//neither is pressed
		{
			motor[armMotor] = 10;      	//hold arm
		}

		// claw
		if(vexRT[Btn6U] == 1)       	//If 6U is pressed
		{
			motor[clawMotor] = 127;  		//close claw
		}
		else if(vexRT[Btn6D] == 1)  	//if 6D is pressed
		{
			motor[clawMotor] = -127; 		//open claw
		}
		else                      		//if neather is pressed
		{
			motor[clawMotor] = 0;    		//do nothing with claw
		}
	}
}
